# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Spectral Stitching'
tagline:          'A haplotype phasing algorithm'
url:              https://chenyx04.github.io
baseurl:          /

author:
  name:           
  url:            https://chenyx04.github.io

paginate:         5



collections:
  people:
    output: true


github:
  repo:       'https://github.com/chenyx04/Spectral-Stitching'

theme: jekyll-theme-dinky
